version: "3.8"

services:
  montage-api:
    build: ./montage
    container_name: montage-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - PERSISTENT_DIR=/app/storage
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=videos
      - MINIO_SECURE=False
      - MINIO_EXTERNAL_URL=https://uniq.powercodeai.space/minio_storage
      - APP_BASE_URL=https://uniq.powercodeai.space
    volumes:
      - ./montage/app:/app
      - ./storage:/app/storage
    depends_on:
      - redis
      - minio
    networks:
      - video-net

  montage-worker:
    build: ./montage
    container_name: montage-worker
    restart: always
    command: celery -A celery_worker.celery_app worker --loglevel=info -Q montage_queue
    environment:
      - PERSISTENT_DIR=/app/storage
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=videos
      - MINIO_SECURE=False
      - MINIO_EXTERNAL_URL=https://uniq.powercodeai.space/minio_storage
    volumes:
      - ./montage/app:/app
      - ./storage:/app/storage
    depends_on:
      - redis
      - minio
      - montage-api
    networks:
      - video-net

  avatar-api:
    build: ./avatar
    container_name: avatar-api
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    env_file:
      - .env 
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PERSISTENT_DIR=/app/storage
      - MONTAGE_SERVICE_URL=http://montage-api:8000
    volumes:
      - ./avatar/app:/app
      - ./storage:/app/storage
    depends_on:
      - redis
    networks:
      - video-net

  avatar-worker:
    build: ./avatar
    container_name: avatar-worker
    restart: always
    command: celery -A celery_worker.celery_app worker --loglevel=info -Q avatar_queue
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PERSISTENT_DIR=/app/storage
      - MONTAGE_SERVICE_URL=http://montage-api:8000
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=videos
      - MINIO_SECURE=False
      - MINIO_EXTERNAL_URL=https://uniq.powercodeai.space/minio_storage
    volumes:
      - ./avatar/app:/app
      - ./storage:/app/storage
    depends_on:
      - redis
      - avatar-api
    networks:
      - video-net

  redis:
    image: redis:alpine
    container_name: video_redis
    ports:
      - "6379:6379"
    networks:
      - video-net

  minio:
    image: minio/minio
    container_name: video_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - video-net

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - montage-api
      - avatar-api
    networks:
      - video-net

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - video-net

networks:
  video-net:

volumes:
  minio_data:
