version: "3.8"

services:
  video-montage:
    build: .
    container_name: video-montage
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - PERSISTENT_DIR=/app/storage
    volumes:
      - ./app:/app
      - ./storage:/app/storage
    networks:
      - video-net

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - video-montage
    networks:
      - video-net

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - video-net

networks:
  video-net: