version: "3.8"

services:
  video-montage:
    build: .
    container_name: video-montage
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - PERSISTENT_DIR=/app/storage
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=videos
      - MINIO_SECURE=False
      - MINIO_EXTERNAL_URL=https://uniq.powercodeai.space/minio_storage
      - APP_BASE_URL=https://uniq.powercodeai.space
    volumes:
      - ./app:/app
      - ./storage:/app/storage
    depends_on:
      - redis
      - minio
    networks:
      - video-net

  celery_worker:
    build: .
    container_name: video_worker
    command: celery -A celery_worker.celery_app worker --loglevel=info
    environment:
      - PERSISTENT_DIR=/app/storage
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=videos
      - MINIO_SECURE=False
      - MINIO_EXTERNAL_URL=https://uniq.powercodeai.space/minio_storage
    volumes:
      - ./app:/app
      - ./storage:/app/storage
    depends_on:
      - redis
      - minio
      - video-montage
    networks:
      - video-net

  redis:
    image: redis:alpine
    container_name: video_redis
    ports:
      - "6379:6379"
    networks:
      - video-net

  minio:
    image: minio/minio
    container_name: video_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - video-net

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - video-montage
    networks:
      - video-net

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - video-net

networks:
  video-net:

volumes:
  minio_data: